### ISSUE TITLE
Can't get short name in multi-VM environment.

### ISSUE THREAD

**Issue by key-amb** [hirose31/vboxss#1]
Hi, this tool is quite handy and very nice.

But I found there is a problem when I run multiple VMs by a single Vagrantfile.
My Vagrantfile is [Here](https://github.com/key-amb/Vagrantfiles/blob/a4e13aa3e60f5d69914450a588e2acd721bd45e6/knife-server-node/Vagrantfile).

And when I launch two VMs, then run **vboxss**, it goes like below:

``` sh
## Vagrantfile is located in ~/Vagrant/bento-centos65/ directory
$ vboxss list
bento-centos65_chef_1429095396402_60198 bento-centos65_chef_1429095396402_60198
bento-centos65_node_1429095435994_29166 bento-centos65_node_1429095435994_29166
```

I doubt that it's caused by the logic of regular-expression matching: here it is - https://github.com/hirose31/vboxss/blob/4668bad050bc46cd4e47e1d520f4f1cf6749d23d/vboxss.go#L117-L118 .

However I don't understand the logic completely.

Is it possible to fix this problem by changing the logic?

Thank you.

**Comment by hirose31** [comment]
Could you use a long name instead of a short name?

**Comment by key-amb** [comment]
Yes, I can.
This is not a big problem at all.

**Comment by key-amb** [comment]
Thanks for merging #2 :laughing:
